# Generated by Django 3.2.4 on 2021-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_auto_20210702_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='read_text',
            field=models.TextField(blank=True, default='author', null=True),
        ),
    ]
